spring.application.name=hivecare-backend

spring.datasource.url=jdbc:mysql://localhost:3306/hivecare
spring.datasource.username=root
spring.datasource.password=803221

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080

razorpay.key.id=rzp_test_TPHP2mcOGLr56L
razorpay.key.secret=tK0232Hxx4HNISh7lxsOCW6n
